version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: winwin-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: auth_db
    ports:
      - "5433:5432"
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d auth_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  data-api:
    build: ./dataapi
    container_name: winwin-data-api
    ports:
      - "8081:8081"
    environment:
      SERVER_PORT: 8081
      APP_INTERNAL_TOKEN: secret-123
    networks:
      - app-network

  auth-api:
    build: ./authapi
    container_name: winwin-auth-api
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/auth_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: root
      APP_INTERNAL_TOKEN: secret-123
      APP_DATA_API_URL: http://data-api:8081
      JWT_SECRET: mySuperSecretKeyForJwtSigning1234567890mySuperSecretKeyForJwtSigning1234567890
    depends_on:
      postgres:
        condition: service_healthy
      data-api:
        condition: service_started
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: